version: 0.0
os: linux

files:             
  - source: /
    destination: /home/ubuntu

hooks:
  ApplicationStop:
   - location: ./applicationStop.sh
     timeout: 180
     runas: ubuntu
  BeforeInstall:
    - location: ./beforeInstall.sh
      timeout: 300
      runas: ubuntu    
  AfterInstall:
   - location: ./afterInstall.sh
     timeout: 180
     runas: ubuntu
  ApplicationStart:
    - location: ./applicationStart.sh
      timeout: 100
      runas: ubuntu