# This workflow will build a Java project with Maven
# For more information see: https://help.github.com/actions/language-and-framework-guides/building-and-testing-java-with-maven

name: Java CI with Maven

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'
        distribution: 'adopt'
    
    - name: Setup MySQL
      uses: mirromutth/mysql-action@v1.1
      with:
        mysql database: getitcheap
        mysql user: getitcheap 
        mysql password: password
        
    - name: Build with Maven
      run: | 
        mvn --quiet -B package --file pom.xml
        pwd
        ls
      
    # Install AWS CLI 2
    - name: Install AWS CLI 2
      run: |
        curl "https://awscli.amazonaws.com/awscli-exe-linux-x86_64.zip" -o "awscliv2.zip"
        unzip awscliv2.zip
        sudo ./aws/install --update
    # Configure AWS credentials
    
    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-1

    - uses: zdurham/s3-upload-github-action@master
      env:
        FILE: ./target/API-0.0.1-SNAPSHOT.jar
        AWS_REGION: 'us-east-1'
        S3_BUCKET: vikram-build-atrifacts
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

    - name: "CodeDeploy"
      run: aws deploy create-deployment --application-name get-it-cheap-code-deploy --deployment-group-name get-it-cheap-deployment-group --s3-location bucket=vikram-build-atrifacts,bundleType=zip,key=webapp-${{ github.run_number }}.zip
   
